import localFont from "next/font/local";
import "./globals.css";
import Navigation from "@/components/navigation";
import Footer from "@/components/footer";

const marri = localFont({
  src: "./fonts/Merriweather.ttf",
  variable: "--font-marri-weather",
  weight: "100 900",
});
const playFair = localFont({
  src: "./fonts/PlayFair.ttf",
  variable: "--font-playfair-display",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${playFair.variable} ${marri.variable} antialiased font-[family-name:var(--font-marri-weather)] bg-[#F7F7F7]`}
      >
        <Navigation />
          {children}
        <Footer />
      </body>
    </html>
  );
}
